config/routes.rb
Rails.application.routes.draw do
  devise_for :instructors

  namespace :instructors do
    resources :enrollment_applications, only: %i[index destroy]
    resources :student_interview_invitations, only: %i[create]
    resources :students
    resources :private_sessions
  end

  resources :affiliate_landings

  get "/sitemap", controller: :sitemap,
                  action: :index

  resources :enrollments do
    resources :payments
  end
end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable,
         :trackable, :validatable

  has_many :private_sessions
end

app/models/private_session.rb
class PrivateSession < ActiveRecord::Base
  belongs_to :student
  belongs_to :instructor

  def ocurred_at_hour
    ts = started_at
    ts.strftime("%b #{ts.day.ordinalize} %l:%M%P").strip
  end

  def student_name
    student && student.name
  end

  def instructor_name
    instructor && instructor.name
  end
end

app/controllers/instructor/application_controller.rb
class Instructor::ApplicationController < ApplicationController
  before_action :authenticate_instructor!

  layout 'instructor'
end

app/controllers/instructor/enrollments_controller.rb
class Instructor::EnrollmentsController < Instructor::ApplicationController
  def index
    enrollments
  end

  def destroy
    Enrollment.find(params[:id]).update_attributes(rejected_at: DateTime.now)
    redirect_to instructor_enrollments_path
  end

private

  def enrollments
    @enrollments = Enrollment.send((params[:q] || 'pending').to_sym)
  end

end

app/controllers/instructors/application_controller.rb
class Instructors::ApplicationController < ApplicationController
  before_action :authenticate_instructor!

  layout 'instructor'
end

app/controllers/instructors/enrollment_applications_controller.rb
class Instructors::EnrollmentApplicationsController < Instructors::ApplicationController
  def index
    enrollment_applications
  end

  def destroy
    Enrollment.find(params[:id]).update_attributes(rejected_at: DateTime.now)
    redirect_to instructors_enrollment_applications_path
  end

private

  def enrollment_applications
    @enrollment_applications ||= Enrollment.send((params[:q] || 'pending').to_sym)
  end

end

app/controllers/instructors/private_sessions_controller.rb
class Instructors::PrivateSessionsController < Instructors::ApplicationController
  def index
    @private_sessions ||= current_instructor.private_sessions
  end

  def show
    private_session
  end

  def new
    new_private_session
  end

  def create
    if new_private_session(private_session_params).save
      redirect_to instructors_private_sessions_path
    else
      render :new
    end
  end

  def edit
    @private_session ||= current_instructor.private_sessions.find(params[:id])
  end

  def update
    if private_session.update_attributes(private_session_params)
      redirect_to instructors_private_sessions_path
    else
      render :edit
    end
  end

private

  def new_private_session(attrs={})
    @private_session ||= current_instructor.private_sessions.build(attrs)
  end

  def private_session
    @private_session ||= current_instructor.private_sessions.find(params[:id])
  end

  def private_session_params
    params.require(:private_session).
      permit(:started_at, :ended_at, :notes,
             :homework, :student_id)
  end
end

app/controllers/instructors/student_interview_invitations_controller.rb
class Instructors::StudentInterviewInvitationsController < Instructors::ApplicationController
  def create
    enrollment = Enrollment.find(params[:enrollment_id])
    enrollment.invite_to_interview!
    redirect_to instructors_enrollment_applications_path
  end

end

app/controllers/instructors/students_controller.rb
class Instructors::StudentsController < Instructors::ApplicationController

  def index
    students
  end

  def destroy
    Student.find(params[:id]).update_attributes(deleted_at: DateTime.now)
    redirect_to instructors_students_path
  end

private

  def students
    @students ||= Student.all
  end

end

app/views/instructors/private_sessions/_form.html.erb
<%= bootstrap_form_for [:instructors, @private_session] do |f| %>
  <%= @private_session.student_name %>
  <%= f.hidden_field :student_id, value: (f.object.student_id || params[:student_id]) %>
  <%= f.text_field :started_at, value: (f.object.started_at || DateTime.now).strftime("%c") %>
  <%= f.text_area :notes, rows: 6 %>
  <%= f.text_area :homework, rows: 6 %>
  <%= f.text_field :ended_at %>

  <%= f.submit %>
<%- end %>

app/views/instructors/private_sessions/_private_session_card.html.erb
<div class="private-session card card-<%= size  %>">
<h3><%= private_session_card.student_name %></h3>
<div class="ocurred-at text-right"><%= private_session_card.ocurred_at_hour %> -
  <%= private_session_card.ended_at &&
        private_session_card.ended_at.strftime("%l:%M%P") %></div>

<% if size == "lg" %>
  <h4>Notes</h4>
  <div class="notes"><%= private_session_card.notes %></div>
  <hr>

  <h4>Homework</h4>
  <div class="homework"><%= private_session_card.homework %></div>
<%- end %>

<div class="text-right">
  <%= link_to "edit", edit_instructors_private_session_path(private_session_card), class:"btn btn-primary" %>
  <% if size == 'sm' %>
    <%= link_to "view", [:instructors, private_session_card], class:"btn btn-secondary" %>
  <%-end %>
</div>
</div>

app/views/instructors/private_sessions/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1>Edit session</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/instructors/private_sessions/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Private Sessions</h1>
<%= render partial: 'private_session_card',
  collection: @private_sessions,
  locals: { size: 'sm' } %>
    </div>
  </div>
</div>

app/views/instructors/private_sessions/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1>Start a new session</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/instructors/private_sessions/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
<%= render partial: 'private_session_card', 
  object: @private_session,
  locals: { size: "lg" } %>
    </div>
  </div>
</div>