config/routes.rb
Rails.application.routes.draw do
  devise_for :instructors

  namespace :instructors do
    resources :enrollment_applications, only: %i[index destroy]
    resources :student_interview_invitations, only: %i[create]
    resources :students
    resources :private_sessions
  end

  resources :affiliate_landings

  get "/sitemap", controller: :sitemap,
                  action: :index

  resources :enrollments do
    resources :payments
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/instructor/application_controller.rb
class Instructor::ApplicationController < ApplicationController
  before_action :authenticate_instructor!

  layout 'instructor'
end

app/controllers/instructors/application_controller.rb
class Instructors::ApplicationController < ApplicationController
  before_action :authenticate_instructor!

  layout 'instructor'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/menus/_instructor.html.erb
<div id="navbar-main"> 
  <div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
        <%= render 'logo' %>
      </div>
      <div class="navbar-collapse collapse">
        <ul id="top-menu" class="nav navbar-nav">
          <li><%= link_to "applications", instructors_enrollment_applications_path %></li>
          <li><%= link_to "students", instructors_students_path %></li>
          <li><%= link_to "logout", destroy_instructor_session_path, method: :delete %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/application/menus/_payment.html.erb
    <div id="navbar-main"> 
      <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
            <%= render 'logo' %>
          </div>
        </div>
      </div>
    </div>