config/routes.rb
Rails.application.routes.draw do
  devise_for :instructors

  namespace :instructors do
    resources :enrollment_applications, only: %i[index destroy]
    resources :student_interview_invitations, only: %i[create]
    resources :students
    resources :private_sessions
  end

  resources :affiliate_landings

  get "/sitemap", controller: :sitemap,
                  action: :index

  resources :enrollments do
    resources :payments
  end
end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable,
         :trackable, :validatable

  has_many :private_sessions
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :enrollment
  has_many :private_sessions

  delegate :name, to: :enrollment
  delegate :enrolled_at, to: :enrollment
  delegate :enrolled_on, to: :enrollment

end

app/controllers/instructor/application_controller.rb
class Instructor::ApplicationController < ApplicationController
  before_action :authenticate_instructor!

  layout 'instructor'
end

app/controllers/instructor/enrollments_controller.rb
class Instructor::EnrollmentsController < Instructor::ApplicationController
  def index
    enrollments
  end

  def destroy
    Enrollment.find(params[:id]).update_attributes(rejected_at: DateTime.now)
    redirect_to instructor_enrollments_path
  end

private

  def enrollments
    @enrollments = Enrollment.send((params[:q] || 'pending').to_sym)
  end

end

app/controllers/instructors/application_controller.rb
class Instructors::ApplicationController < ApplicationController
  before_action :authenticate_instructor!

  layout 'instructor'
end

app/controllers/instructors/enrollment_applications_controller.rb
class Instructors::EnrollmentApplicationsController < Instructors::ApplicationController
  def index
    enrollment_applications
  end

  def destroy
    Enrollment.find(params[:id]).update_attributes(rejected_at: DateTime.now)
    redirect_to instructors_enrollment_applications_path
  end

private

  def enrollment_applications
    @enrollment_applications ||= Enrollment.send((params[:q] || 'pending').to_sym)
  end

end

app/controllers/instructors/private_sessions_controller.rb
class Instructors::PrivateSessionsController < Instructors::ApplicationController
  def index
    @private_sessions ||= current_instructor.private_sessions
  end

  def show
    private_session
  end

  def new
    new_private_session
  end

  def create
    if new_private_session(private_session_params).save
      redirect_to instructors_private_sessions_path
    else
      render :new
    end
  end

  def edit
    @private_session ||= current_instructor.private_sessions.find(params[:id])
  end

  def update
    if private_session.update_attributes(private_session_params)
      redirect_to instructors_private_sessions_path
    else
      render :edit
    end
  end

private

  def new_private_session(attrs={})
    @private_session ||= current_instructor.private_sessions.build(attrs)
  end

  def private_session
    @private_session ||= current_instructor.private_sessions.find(params[:id])
  end

  def private_session_params
    params.require(:private_session).
      permit(:started_at, :ended_at, :notes,
             :homework, :student_id)
  end
end

app/controllers/instructors/student_interview_invitations_controller.rb
class Instructors::StudentInterviewInvitationsController < Instructors::ApplicationController
  def create
    enrollment = Enrollment.find(params[:enrollment_id])
    enrollment.invite_to_interview!
    redirect_to instructors_enrollment_applications_path
  end

end

app/controllers/instructors/students_controller.rb
class Instructors::StudentsController < Instructors::ApplicationController

  def index
    students
  end

  def destroy
    Student.find(params[:id]).update_attributes(deleted_at: DateTime.now)
    redirect_to instructors_students_path
  end

private

  def students
    @students ||= Student.all
  end

end

app/views/instructors/students/_student.html.erb
<div class="pull-left student card-sm">
<div class="name"><strong><%= student.name %></strong></div>
  <div class="enrolled-on">Enrolled on: <%= student.enrollment.enrolled_on %></div>
  <div class="session-count">Session count: <%= student.private_sessions.count %></div>
  <div class="sessions-left">Sessions left: <%= student.enrollment.private_sessions_left %></div>
  <div class="weeks-left">Weeks left: <%= student.enrollment.weeks_left %></div>

  <div class="text-center">
    <%= link_to "new session", new_instructors_private_session_path(student_id: student.id) %>
    | <%= link_to "view history", instructors_private_sessions_path %></div>
</div>

app/views/instructors/students/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Enrolled Students</h1>
      <%= render partial: 'student', collection: @students %>
    </div>
  </div>
</div>

app/views/instructors/students/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1>Send a new student invite</h1>
<%= form_for [:instructors, @student] do |f| %>
  <%= f.text_field :email %>
  <%= f.submit "Invite to program" %>
<%-end %>
    </div>
  </div>
</div>