config/routes.rb
Rails.application.routes.draw do
  devise_for :instructors

  namespace :instructors do
    resources :enrollment_applications, only: %i[index destroy]
    resources :student_interview_invitations, only: %i[create]
    resources :students
    resources :private_sessions
  end

  resources :affiliate_landings

  get "/sitemap", controller: :sitemap,
                  action: :index

  resources :enrollments do
    resources :payments
  end
end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable,
         :trackable, :validatable

  has_many :private_sessions
end

app/controllers/instructor/application_controller.rb
class Instructor::ApplicationController < ApplicationController
  before_action :authenticate_instructor!

  layout 'instructor'
end

app/controllers/instructor/enrollments_controller.rb
class Instructor::EnrollmentsController < Instructor::ApplicationController
  def index
    enrollments
  end

  def destroy
    Enrollment.find(params[:id]).update_attributes(rejected_at: DateTime.now)
    redirect_to instructor_enrollments_path
  end

private

  def enrollments
    @enrollments = Enrollment.send((params[:q] || 'pending').to_sym)
  end

end

app/controllers/instructors/application_controller.rb
class Instructors::ApplicationController < ApplicationController
  before_action :authenticate_instructor!

  layout 'instructor'
end

app/controllers/instructors/enrollment_applications_controller.rb
class Instructors::EnrollmentApplicationsController < Instructors::ApplicationController
  def index
    enrollment_applications
  end

  def destroy
    Enrollment.find(params[:id]).update_attributes(rejected_at: DateTime.now)
    redirect_to instructors_enrollment_applications_path
  end

private

  def enrollment_applications
    @enrollment_applications ||= Enrollment.send((params[:q] || 'pending').to_sym)
  end

end

app/controllers/instructors/private_sessions_controller.rb
class Instructors::PrivateSessionsController < Instructors::ApplicationController
  def index
    @private_sessions ||= current_instructor.private_sessions
  end

  def show
    private_session
  end

  def new
    new_private_session
  end

  def create
    if new_private_session(private_session_params).save
      redirect_to instructors_private_sessions_path
    else
      render :new
    end
  end

  def edit
    @private_session ||= current_instructor.private_sessions.find(params[:id])
  end

  def update
    if private_session.update_attributes(private_session_params)
      redirect_to instructors_private_sessions_path
    else
      render :edit
    end
  end

private

  def new_private_session(attrs={})
    @private_session ||= current_instructor.private_sessions.build(attrs)
  end

  def private_session
    @private_session ||= current_instructor.private_sessions.find(params[:id])
  end

  def private_session_params
    params.require(:private_session).
      permit(:started_at, :ended_at, :notes,
             :homework, :student_id)
  end
end

app/controllers/instructors/student_interview_invitations_controller.rb
class Instructors::StudentInterviewInvitationsController < Instructors::ApplicationController
  def create
    enrollment = Enrollment.find(params[:enrollment_id])
    enrollment.invite_to_interview!
    redirect_to instructors_enrollment_applications_path
  end

end

app/controllers/instructors/students_controller.rb
class Instructors::StudentsController < Instructors::ApplicationController

  def index
    students
  end

  def destroy
    Student.find(params[:id]).update_attributes(deleted_at: DateTime.now)
    redirect_to instructors_students_path
  end

private

  def students
    @students ||= Student.all
  end

end

app/views/instructors/enrollment_applications/_interviewing.html.erb
<h1>interviewing applications</h1>
<%= render 'menu' %>
<table class="table table-striped table-responsive">
  <tr>
    <th>ID</th>
    <th>Emailed on</th>
    <th>Name</th>
    <th>Email</th>
    <th></th>
  </tr>
  <%= render partial: 'interviewing_row', collection: interviewing %>
</table>

app/views/instructors/enrollment_applications/_interviewing_row.html.erb
  <tr>
    <td><%= interviewing_row.id %></td>
    <td><%= interviewing_row.interview_invitation_sent_on %></td>
    <td><%= interviewing_row.name %></td>
    <td><%= interviewing_row.email %></td>
    <td><%= link_to "reject", instructors_enrollment_application_path(interviewing_row), method: :delete, data: { confirm: "You are about to reject #{interviewing_row.name}'s application. Are you sure?" } %></td>
    </td>
  </tr>

app/views/instructors/enrollment_applications/_menu.html.erb
<ul class="list-inline list-unstyled center-block">
<li><a class="pill <%= "active" if params[:q].nil? || params[:q] == "pending" %>" href="?q=pending">Pending</a></li>
  <li><a class="pill <%= "active" if params[:q] == "interviewing" %>" href="?q=interviewing">Interviewing</a></li>
  <li><a class="pill <%= "active" if params[:q] == "rejected" %>" href="?q=rejected">Rejected</a></li>
</ul>

app/views/instructors/enrollment_applications/_pending.html.erb
<h1>Pending applications</h1>
<%= render 'menu' %>
<table class="table table-striped table-responsive">
  <tr>
    <th>ID</th>
    <th>Applied on</th>
    <th>Promo</th>
    <th>Name</th>
    <th>Email</th>
    <th>Github</th>
    <th>Why?</th>
    <th></th>
    <th></th>
  </tr>
  <%= render partial: 'pending_row', collection: pending %>
</table>

app/views/instructors/enrollment_applications/_pending_row.html.erb
  <tr>
    <td><%= pending_row.id %></td>
    <td><%= pending_row.applied_on %></td>
    <td><%= pending_row.promo_code %></td>
    <td><%= pending_row.name %></td>
    <td><%= pending_row.email %></td>
    <td><%= pending_row.github_url %></td>
    <td><%= pending_row.why %></td>
    <td><%= link_to "interview", instructors_student_interview_invitations_path(enrollment_id: pending_row), method: :post, data: { confirm: "You are about to email #{pending_row.name} and ask them to interview at Devschool. Are you sure?" } %></td>
    <td><%= link_to "reject", instructors_enrollment_application_path(pending_row), method: :delete, data: { confirm: "You are about to reject #{pending_row.name}'s application. Are you sure?" } %></td>
    </td>
  </tr>

app/views/instructors/enrollment_applications/_rejected.html.erb
<h1>Rejected applications</h1>
<%= render 'menu' %>
<table class="table table-striped table-responsive">
  <tr>
    <th>Rejected on</th>
    <th>Student name</th>
    <th>Email</th>
  </tr>
  <%= render partial: 'rejected_row', collection: rejected %>
</table>

app/views/instructors/enrollment_applications/_rejected_row.html.erb
  <tr>
    <td><%= rejected_row.rejected_on %></td>
    <td><%= rejected_row.name %></td>
    <td><%= rejected_row.email %></td>
  </tr>

app/views/instructors/enrollment_applications/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= render partial: (params[:q] || 'pending'),
        object: @enrollment_applications %>
    </div>
  </div>
</div>